export const ADD_ADDRESS = 'ADD_ADDRESS';
export const FETCH_START = 'FETCH_START';
export const FETCH_FAILED= 'FETCH_FAILED';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ADDRESS = 'FETCH_ADDRESS';
